souffle: souffle::RamAbstractExistenceCheck Class Reference
souffle::RamAbstractExistenceCheck Class Reference
Abstract existence check.
#include <RamCondition.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelationReference & getRelation () const
Get relation.
std::vector< RamValue * > getValues () const
Get arguments.
RamAbstractExistenceCheck (RamNodeType type, std::unique_ptr< RamRelationReference > rel, std::vector< std::unique_ptr< RamValue >> vals)
Public Member Functions inherited from souffle::RamCondition
RamCondition * clone () const override=0
Create clone.
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
virtual void print (std::ostream &out=std::cout) const =0
Print RAM node.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamRelationReference > relation
std::vector< std::unique_ptr< RamValue > > values
Pattern – nullptr if undefined.
Detailed Description
Abstract existence check.
Definition at line 231 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamAbstractExistenceCheck::RamAbstractExistenceCheck (RamNodeType type, std::unique_ptr< RamRelationReference > rel, std::vector< std::unique_ptr< RamValue >> vals) inline
Definition at line 240 of file RamCondition.h.
             : RamCondition(type), relation(std::move(rel)), values(std::move(vals)) {}
Member Function Documentation
void souffle::RamAbstractExistenceCheck::apply (const RamNodeMapper & map) inline override virtual
Apply.
Implements souffle::RamNode.
Definition at line 264 of file RamCondition.h.
{
         relation = map(std::move(relation));
         for (auto& val : values) {
             if (val != nullptr) {
                 val = map(std::move(val));
             }
         }
     }
bool souffle::RamAbstractExistenceCheck::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Reimplemented in souffle::RamProvenanceExistenceCheck, and souffle::RamExistenceCheck.
Definition at line 275 of file RamCondition.h.
References souffle::equal_targets(), and getRelation().
Referenced by souffle::RamExistenceCheck::equal(), and souffle::RamProvenanceExistenceCheck::equal().
{
         assert(nullptr != dynamic_cast<const RamAbstractExistenceCheck*>(&node));
         const auto& other = static_cast<const RamAbstractExistenceCheck&>(node);
         return getRelation() == other.getRelation() && equal_targets(values, other.values);
     }
std::vector<const RamNode*> souffle::RamAbstractExistenceCheck::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 255 of file RamCondition.h.
{
         std::vector<const RamNode*> res = {relation.get()};
         for (const auto& cur : values) {
             res.push_back(cur.get());
         }
         return res;
     }
const RamRelationReference& souffle::RamAbstractExistenceCheck::getRelation () const inline
Get relation.
Definition at line 245 of file RamCondition.h.
References relation.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalCond().
{
         return *relation;
     }
std::vector<RamValue*> souffle::RamAbstractExistenceCheck::getValues () const inline
Get arguments.
Definition at line 250 of file RamCondition.h.
References souffle::toPtrVector().
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), souffle::RamExistenceCheckAnalysis::getKey(), souffle::RamProvenanceExistenceCheckAnalysis::getKey(), souffle::RamConditionLevelAnalysis::getLevel(), souffle::getLevel(), souffle::RamProvenanceExistenceCheckAnalysis::isTotal(), and souffle::RamExistenceCheckAnalysis::isTotal().
{
         return toPtrVector(values);
     }
Field Documentation
std::unique_ptr<RamRelationReference> souffle::RamAbstractExistenceCheck::relation protected
Definition at line 234 of file RamCondition.h.
std::vector<std::unique_ptr<RamValue> > souffle::RamAbstractExistenceCheck::values protected
Pattern – nullptr if undefined.
Definition at line 237 of file RamCondition.h.
The documentation for this class was generated from the following file:
RamCondition.h