souffle: souffle::RamProvenanceExistenceCheck Class Reference
souffle::RamProvenanceExistenceCheck Class Reference
Existence check for a relation for provenance existence check.
#include <RamCondition.h>
Public Member Functions
RamProvenanceExistenceCheck * clone () const override
Create clone.
void print (std::ostream &os) const override
Print.
RamProvenanceExistenceCheck (std::unique_ptr< RamRelationReference > rel, std::vector< std::unique_ptr< RamValue >> vals)
Public Member Functions inherited from souffle::RamAbstractExistenceCheck
void apply (const RamNodeMapper &map) override
Apply.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamRelationReference & getRelation () const
Get relation.
std::vector< RamValue * > getValues () const
Get arguments.
RamAbstractExistenceCheck (RamNodeType type, std::unique_ptr< RamRelationReference > rel, std::vector< std::unique_ptr< RamValue >> vals)
Public Member Functions inherited from souffle::RamCondition
RamCondition (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Additional Inherited Members
Protected Attributes inherited from souffle::RamAbstractExistenceCheck
std::unique_ptr< RamRelationReference > relation
std::vector< std::unique_ptr< RamValue > > values
Pattern – nullptr if undefined.
Detailed Description
Existence check for a relation for provenance existence check.
Definition at line 330 of file RamCondition.h.
Constructor & Destructor Documentation
souffle::RamProvenanceExistenceCheck::RamProvenanceExistenceCheck (std::unique_ptr< RamRelationReference > rel, std::vector< std::unique_ptr< RamValue >> vals) inline
Definition at line 332 of file RamCondition.h.
             : RamAbstractExistenceCheck(RN_ProvenanceExistenceCheck, std::move(rel), std::move(vals)) {}
Member Function Documentation
RamProvenanceExistenceCheck* souffle::RamProvenanceExistenceCheck::clone () const inline override virtual
Create clone.
Implements souffle::RamCondition.
Definition at line 351 of file RamCondition.h.
References souffle::RamValue::clone(), and relation.
{
         std::vector<std::unique_ptr<RamValue>> newValues;
         for (auto& cur : values) {
             RamValue* val = nullptr;
             if (cur != nullptr) {
                 val = cur->clone();
             }
             newValues.emplace_back(val);
         }
         RamProvenanceExistenceCheck* res = new RamProvenanceExistenceCheck(
                 std::unique_ptr<RamRelationReference>(relation->clone()), std::move(newValues));
         return res;
     }
bool souffle::RamProvenanceExistenceCheck::equal (const RamNode & node) const inline override protected virtual
Check equality.
Reimplemented from souffle::RamAbstractExistenceCheck.
Definition at line 367 of file RamCondition.h.
References souffle::RamAbstractExistenceCheck::equal().
{
         assert(dynamic_cast<const RamProvenanceExistenceCheck*>(&node));
         return RamAbstractExistenceCheck::equal(node);
     }
void souffle::RamProvenanceExistenceCheck::print (std::ostream & os) const inline override virtual
Print.
Implements souffle::RamNode.
Definition at line 337 of file RamCondition.h.
References souffle::join(), and relation.
{
         os << "("
            << join(values, ",",
                       [](std::ostream& out, const std::unique_ptr<RamValue>& value) {
                           if (!value) {
                               out << "_";
                           } else {
                               out << *value;
                           }
                       })
            << ") prov∈ " << relation->getName();
     }
The documentation for this class was generated from the following file:
RamCondition.h