souffle: souffle::RamRelationReference Class Reference
souffle::RamRelationReference Class Reference
A RAM Relation in the RAM intermediate representation.
#include <RamRelation.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamRelationReference * clone () const override
Create clone.
const std::string getArg (uint32_t i) const
Get argument.
const std::string getArgTypeQualifier (uint32_t i) const
Get argument qualifier.
unsigned getArity () const
Get arity.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const std::string & getName () const
Get name.
const RamRelation * getRelation () const
Get relation.
const RelationRepresentation getRepresentation () const
Relation representation type.
const SymbolMask & getSymbolMask () const
Get symbol mask.
const bool isNullary () const
Is nullary relation.
const bool isTemp () const
Is temp relation.
bool operator< (const RamRelationReference &other) const
Comparator.
void print (std::ostream &out) const override
Print RAM node.
RamRelationReference (const RamRelation *relation)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
const RamRelation * relation
Name of relation.
Detailed Description
A RAM Relation in the RAM intermediate representation.
Definition at line 167 of file RamRelation.h.
Constructor & Destructor Documentation
souffle::RamRelationReference::RamRelationReference (const RamRelation * relation) inline
Definition at line 173 of file RamRelation.h.
 : RamNode(RN_RelationReference), relation(relation) {}
Member Function Documentation
void souffle::RamRelationReference::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 242 of file RamRelation.h.
 {}
RamRelationReference* souffle::RamRelationReference::clone () const inline override virtual
Create clone.
Implements souffle::RamNode.
Definition at line 236 of file RamRelation.h.
Referenced by souffle::AstTranslator::ClauseTranslator::indexValues(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         auto* res = new RamRelationReference(relation);
         return res;
     }
bool souffle::RamRelationReference::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 246 of file RamRelation.h.
{
         assert(nullptr != dynamic_cast<const RamRelationReference*>(&node));
         const auto& other = static_cast<const RamRelationReference&>(node);
         return relation == other.relation;
     }
const std::string souffle::RamRelationReference::getArg (uint32_t i) const inline
Get argument.
Definition at line 211 of file RamRelation.h.
References souffle::RamRelation::getArg().
Referenced by souffle::RamIndexScan::print(), and souffle::IndexSetAnalysis::print().
{
         return relation->getArg(i);
     }
const std::string souffle::RamRelationReference::getArgTypeQualifier (uint32_t i) const inline
Get argument qualifier.
Definition at line 216 of file RamRelation.h.
References souffle::RamRelation::getArgTypeQualifier().
{
         return relation->getArgTypeQualifier(i);
     }
unsigned souffle::RamRelationReference::getArity () const inline
Get arity.
Definition at line 186 of file RamRelation.h.
References souffle::RamRelation::getArity().
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalOp(), souffle::Interpreter::evalStmt(), souffle::Synthesiser::generateCode(), souffle::SynthesiserRelation::getArity(), souffle::SynthesiserRelation::getSynthesiserRelation(), souffle::RamIndexScan::print(), souffle::IndexSetAnalysis::print(), and souffle::CreateIndicesTransformer::rewriteScan().
{
         return relation->getArity();
     }
std::vector<const RamNode*> souffle::RamRelationReference::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 231 of file RamRelation.h.
{
         return std::vector<const RamNode*>();  // no child nodes
     }
const std::string& souffle::RamRelationReference::getName () const inline
Get name.
Definition at line 176 of file RamRelation.h.
References souffle::RamRelation::getName().
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), souffle::Interpreter::evalStmt(), souffle::Interpreter::executeMain(), souffle::Synthesiser::generateCode(), souffle::IndexSetAnalysis::getIndexes(), souffle::Synthesiser::getRelationName(), souffle::RamIndexScan::print(), and souffle::Interpreter::swapRelation().
{
         return relation->getName();
     }
const RamRelation* souffle::RamRelationReference::getRelation () const inline
Get relation.
Definition at line 181 of file RamRelation.h.
References relation.
Referenced by operator<().
{
         return relation;
     }
const RelationRepresentation souffle::RamRelationReference::getRepresentation () const inline
Relation representation type.
Definition at line 196 of file RamRelation.h.
References souffle::RamRelation::getRepresentation().
Referenced by souffle::Synthesiser::emitCode(), and souffle::SynthesiserRelation::getSynthesiserRelation().
{
         return relation->getRepresentation();
     }
const SymbolMask& souffle::RamRelationReference::getSymbolMask () const inline
Get symbol mask.
Definition at line 206 of file RamRelation.h.
References souffle::RamRelation::getSymbolMask().
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalStmt(), and souffle::Synthesiser::generateCode().
{
         return relation->getSymbolMask();
     }
const bool souffle::RamRelationReference::isNullary () const inline
Is nullary relation.
Definition at line 191 of file RamRelation.h.
References souffle::RamRelation::isNullary().
Referenced by souffle::Synthesiser::emitCode(), and souffle::SynthesiserRelation::getSynthesiserRelation().
{
         return relation->isNullary();
     }
const bool souffle::RamRelationReference::isTemp () const inline
Is temp relation.
Definition at line 201 of file RamRelation.h.
References souffle::RamRelation::isTemp().
Referenced by souffle::Synthesiser::emitCode(), souffle::Interpreter::evalCond(), and souffle::Synthesiser::generateCode().
{
         return relation->isTemp();
     }
bool souffle::RamRelationReference::operator< (const RamRelationReference & other) const inline
Comparator.
Definition at line 221 of file RamRelation.h.
References getRelation().
{
         return relation->operator<(*other.getRelation());
     }
void souffle::RamRelationReference::print (std::ostream & out) const inline override virtual
Print RAM node.
Implements souffle::RamNode.
Definition at line 226 of file RamRelation.h.
References souffle::RamRelation::getName().
{
         out << getName();
     }
Field Documentation
const RamRelation* souffle::RamRelationReference::relation protected
Name of relation.
Definition at line 170 of file RamRelation.h.
The documentation for this class was generated from the following file:
RamRelation.h