souffle: souffle::RamQuery Class Reference
souffle::RamQuery Class Reference
A relational algebra query.
#include <RamStatement.h>
Public Member Functions
void apply (const RamNodeMapper &map) override
Apply mapper.
RamQuery * clone () const override
Create clone.
std::vector< const RamNode * > getChildNodes () const override
Obtain list of child nodes.
const RamCondition * getCondition () const
Get RAM condition.
const RamOperation & getOperation () const
Get RAM operation.
void print (std::ostream &os, int tabpos) const override
Pretty print.
RamQuery (std::unique_ptr< RamOperation > o, std::unique_ptr< RamCondition > c=nullptr)
void setOperation (std::unique_ptr< RamOperation > nested)
Sets the nested operation.
Public Member Functions inherited from souffle::RamStatement
void print (std::ostream &os) const override
Print RAM statement.
RamStatement (RamNodeType type)
Public Member Functions inherited from souffle::RamNode
RamNodeType getNodeType () const
Get type of node.
bool operator!= (const RamNode &other) const
Inequality check for two RAM nodes.
bool operator== (const RamNode &other) const
Equivalence check for two RAM nodes.
RamNode (RamNodeType type)
virtual ~RamNode ()=default
A virtual destructor for RAM nodes.
Protected Member Functions
bool equal (const RamNode &node) const override
Check equality.
Protected Attributes
std::unique_ptr< RamCondition > condition
RAM condition.
std::unique_ptr< RamOperation > operation
RAM operation.
Detailed Description
A relational algebra query.
Definition at line 406 of file RamStatement.h.
Constructor & Destructor Documentation
souffle::RamQuery::RamQuery (std::unique_ptr< RamOperation > o, std::unique_ptr< RamCondition > c = nullptr) inline
Definition at line 415 of file RamStatement.h.
             : RamStatement(RN_Query), operation(std::move(o)), condition(std::move(c)) {}
Member Function Documentation
void souffle::RamQuery::apply (const RamNodeMapper & map) inline override virtual
Apply mapper.
Implements souffle::RamNode.
Definition at line 464 of file RamStatement.h.
{
         operation = map(std::move(operation));
         if (condition != nullptr) {
             condition = map(std::move(condition));
         }
     }
RamQuery* souffle::RamQuery::clone () const inline override virtual
Create clone.
Implements souffle::RamStatement.
Definition at line 452 of file RamStatement.h.
{
         RamQuery* res;
         if (condition != nullptr) {
             res = new RamQuery(std::unique_ptr<RamOperation>(operation->clone()));
         } else {
             res = new RamQuery(std::unique_ptr<RamOperation>(operation->clone()),
                     std::unique_ptr<RamCondition>(condition->clone()));
         }
         return res;
     }
bool souffle::RamQuery::equal (const RamNode & node) const inline override protected virtual
Check equality.
Implements souffle::RamNode.
Definition at line 473 of file RamStatement.h.
References getOperation().
{
         assert(nullptr != dynamic_cast<const RamQuery*>(&node));
         const auto& other = static_cast<const RamQuery&>(node);
         return getOperation() == other.getOperation() && getCondition() == other.getCondition();
     }
std::vector<const RamNode*> souffle::RamQuery::getChildNodes () const inline override virtual
Obtain list of child nodes.
Implements souffle::RamNode.
Definition at line 447 of file RamStatement.h.
{
         return std::vector<const RamNode*>({operation.get(), condition.get()});
     }
const RamCondition* souffle::RamQuery::getCondition () const inline
Get RAM condition.
Definition at line 430 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), and souffle::Interpreter::evalStmt().
{
         return condition.get();
     }
const RamOperation& souffle::RamQuery::getOperation () const inline
Get RAM operation.
Definition at line 419 of file RamStatement.h.
Referenced by souffle::Synthesiser::emitCode(), equal(), and souffle::Interpreter::evalStmt().
{
         assert(operation);
         return *operation;
     }
void souffle::RamQuery::print (std::ostream & os, int tabpos) const inline override virtual
Pretty print.
Implements souffle::RamStatement.
Definition at line 435 of file RamStatement.h.
{
         os << std::string(tabpos, '\t');
         os << "DO ";
         if (condition != nullptr) {
             os << "WHERE ";
             condition->print(os);
         }
         os << "\n";
         operation->print(os, tabpos + 1);
     }
void souffle::RamQuery::setOperation (std::unique_ptr< RamOperation > nested) inline
Sets the nested operation.
Definition at line 425 of file RamStatement.h.
{
         operation = std::move(nested);
     }
Field Documentation
std::unique_ptr<RamCondition> souffle::RamQuery::condition protected
RAM condition.
Definition at line 412 of file RamStatement.h.
std::unique_ptr<RamOperation> souffle::RamQuery::operation protected
RAM operation.
Definition at line 409 of file RamStatement.h.
The documentation for this class was generated from the following file:
RamStatement.h